# Config file for Festival

# Festival options
Options:
  
  # Messages (tip/pop)  
  Msgtype: pop
  
  # Messages persist display to ops (off/op/on)
  Msgdisplay: off
  
  # Auto whitelist area creator (on/off)
  AutoWhitelist: on

# Settings for unprotected areas in worlds without specific settings:
Default:

  # Keep players from getting hurt?  
  God: false

  # Keep players from getting hurt by other players?
  PVP: false

  # Keep players from flying?
  Flight: false

  # Keep players from editing the world?
  Edit: false

  # Keep players from touching blocks and activating things like chests?
  Touch: false
  
  # Keep players from having effects like speed or night vision?
  Effects: false
   
  # Keep players from seeing enter/leave/description messages?
  Msg: false

  # Prevent players enter/leaving the area? Deny passage (previously barrier)
  Passage: false

  # Prevent players drop items in the area? Deny drop
  Drop: false

  # Player permission overwrite for area event command execution
  Perms: false

# Settings for unprotected areas in individual worlds:
Worlds:
 
  DEFAULT:

    # Keep players from getting hurt? 
    God: false

    # Keep players from getting hurt by other players?
    PVP: false

    # Keep players from getting hurt by other players?
    Flight: false

    # Keep players from editing the world?
    Edit: true

    # Keep players from touching blocks and activating things like chests?
    Touch: false
  
    # Keep players from touching blocks and activating things like chests?
    Effects: false

    # Keep players from seeing enter/leave/description messages?
    Msg: false

    # Prevent players from enter/leaving the area? (previously barrier)
    Passage: false

    # Prevent players drop items in the area? Deny drop
    Drop: false

    # Player permission overwrite for area event command execution
    Perms: false

  World:
  
    # Keep players from getting hurt? 
    God: false

    # Keep players from getting hurt by other players?
    PVP: false

    # Keep players from getting hurt by other players?
    Flight: false

    # Keep players from editing the world?
    Edit: false

    # Keep players from touching blocks and activating things like chests?
    Touch: false
  
    # Keep players from touching blocks and activating things like chests?
    Effects: false

    # Keep players from seeing enter/leave/description messages?
    Msg: false

    # Prevent players from enter/leaving the area? (previously barrier)
    Passage: false

    # Prevent players drop items in the area? Deny drop
    Drop: false
 
    # Player permission overwrite for area event command execution
    Perms: false
