# Config file for Festival

# Festival options
Options:
  
  # Messages (tip/pop)  
  Msgtype: pop
  
  # Messages persist display to ops (off/op/on)
  Msgdisplay: off
  
  # Auto whitelist area creator (on/off)
  AutoWhitelist: on

# Settings for unprotected areas in worlds without specific settings:
Default:

  # Keep players from getting hurt?  
  God: false

  # Keep players from getting hurt by other players?
  PVP: false

  # Keep players from flying?
  Flight: true

  # Keep players from editing the world?
  Edit: true

  # Keep players from touching blocks and activating things like chests?
  Touch: false
  
  # Keep players from having effects like speed or night vision?
  Effects: false
   
  # Keep players from seeing enter/leave/description messages?
  Msg: false

  # Prevent players from enter/leaving the area? (barrier)
  Passage: false

  # Keep players from dropping items in the area?
  Drop: false

  # No explosions allowed in the area?
  TNT: false

  # No shooting allowed in the area?
  Shoot: false

  # Keep players from hunger(exhaust) in the area?
  Hunger: false

  # Keep players from executing area event commands without specific perms
  Perms: false
  
  # Keep players from taking fall damage (default for teleport/flying drop)
  NoFallDamage: true
  
# Settings for unprotected areas in individual worlds:
Worlds:
 
  DEFAULT:

    # Keep players from getting hurt? 
    God: false

    # Keep players from getting hurt by other players?
    PVP: false

    # Keep players from flying?
    Flight: true

    # Keep players from editing the world?
    Edit: true

    # Keep players from touching blocks and activating things like chests?
    Touch: false
  
    # Keep players from touching blocks and activating things like chests?
    Effects: false

    # Keep players from seeing enter/leave/description messages?
    Msg: false

    # Prevent players from enter/leaving the area? (barrier)
    Passage: false

    # No explosions allowed in the area?
    Drop: false

    # No explosions allowed in the area?
    TNT: false

    # No shooting allowed in the area?
    Shoot: false

    # Keep players from hunger(exhaust) in the area?
    Hunger: false

    # Keep players from executing area event commands without specific perms
    Perms: false

    # Keep players from taking fall damage
    NoFallDamage: true

  world:
  
    # Keep players from getting hurt? 
    God: false

    # Keep players from getting hurt by other players?
    PVP: false

    # Keep players from flying?
    Flight: true

    # Keep players from editing the world?
    Edit: true

    # Keep players from touching blocks and activating things like chests?
    Touch: false
  
    # Keep players from touching blocks and activating things like chests?
    Effects: false

    # Keep players from seeing enter/leave/description messages?
    Msg: false

    # Prevent players from enter/leaving the area? (barrier)
    Passage: false

    # Keep players from dropping items in the area?
    Drop: false

    # No explosions allowed in the area?
    TNT: false

    # No shooting allowed in the area?
    Shoot: false

    # Keep players from hunger(exhaust) in the area?
    Hunger: false

    # Keep players from executing area event commands without specific perms
    Perms: false

    # Keep players from taking fall damage
    NoFallDamage: true
